// AUTO-GENERATED by scripts/generate-project-index.ts — DO NOT EDIT
import { Project } from "@/types/project";

import data0 from "./projects/2020-advanced.json";
import data1 from "./projects/2020-it.json";
import data2 from "./projects/2021-advanced.json";
import data3 from "./projects/2021-it.json";
import data4 from "./projects/2022-advanced.json";
import data5 from "./projects/2022-it.json";
import data6 from "./projects/2023-advanced.json";
import data7 from "./projects/2023-it.json";
import data8 from "./projects/2024-advanced.json";
import data9 from "./projects/2024-it.json";
import data10 from "./projects/2025-advanced.json";
import data11 from "./projects/2025-it.json";

export const projects: Project[] = [...data0, ...data1, ...data2, ...data3, ...data4, ...data5, ...data6, ...data7, ...data8, ...data9, ...data10, ...data11] as Project[];
