// AUTO-GENERATED by scripts/generate-project-index.ts — DO NOT EDIT
import { Project } from "@/types/project";

import data0 from "./projects/2008-it.json";
import data1 from "./projects/2009-it.json";
import data2 from "./projects/2010-it.json";
import data3 from "./projects/2011-it.json";
import data4 from "./projects/2012-it.json";
import data5 from "./projects/2013-it.json";
import data6 from "./projects/2014-it.json";
import data7 from "./projects/2015-it.json";
import data8 from "./projects/2016-it.json";
import data9 from "./projects/2017-advanced.json";
import data10 from "./projects/2017-it.json";
import data11 from "./projects/2018-advanced.json";
import data12 from "./projects/2018-it.json";
import data13 from "./projects/2019-advanced.json";
import data14 from "./projects/2019-it.json";
import data15 from "./projects/2020-advanced.json";
import data16 from "./projects/2020-it.json";
import data17 from "./projects/2021-advanced.json";
import data18 from "./projects/2021-it.json";
import data19 from "./projects/2022-advanced.json";
import data20 from "./projects/2022-it.json";
import data21 from "./projects/2023-advanced.json";
import data22 from "./projects/2023-it.json";
import data23 from "./projects/2024-advanced.json";
import data24 from "./projects/2024-it.json";
import data25 from "./projects/2025-advanced.json";
import data26 from "./projects/2025-it.json";

export const projects: Project[] = [...data0, ...data1, ...data2, ...data3, ...data4, ...data5, ...data6, ...data7, ...data8, ...data9, ...data10, ...data11, ...data12, ...data13, ...data14, ...data15, ...data16, ...data17, ...data18, ...data19, ...data20, ...data21, ...data22, ...data23, ...data24, ...data25, ...data26] as Project[];
